divisions = {
    {
        id = "R1",
        owner = "red",
        position = 10,
        infantry = 10,
        arty = 5,
    },
    {
        id = "R2",
        owner = "red",
        position = 30,
        infantry = 8,
        arty = 3,
    },
	{
        id = "R2",
        owner = "red",
        position = 50,
        infantry = 8,
        arty = 3,
    },
	{
        id = "R2",
        owner = "red",
        position = 70,
        infantry = 8,
        arty = 3,
    },
	{
        id = "R2",
        owner = "red",
        position = 90,
        infantry = 8,
        arty = 3,
    },
	{
        id = "R2",
        owner = "red",
        position = 110,
        infantry = 8,
        arty = 3,
    },
	{
        id = "R2",
        owner = "red",
        position = 130,
        infantry = 8,
        arty = 3,
    },
	{
        id = "R2",
        owner = "red",
        position = 150,
        infantry = 8,
        arty = 3,
    },
	{
        id = "R2",
        owner = "red",
        position = 170,
        infantry = 8,
        arty = 3,
    },
	{
        id = "R2",
        owner = "red",
        position = 190,
        infantry = 8,
        arty = 3,
    },
    {
        id = "B1",
        owner = "blue",
        position = 11,
        infantry = 0,
        arty = 1,
    },
    {
        id = "B2",
        owner = "blue",
        position = 31,
        infantry = 7,
        arty = 2,
    },
	{
        id = "B2",
        owner = "blue",
        position = 51,
        infantry = 7,
        arty = 2,
    },
	{
        id = "B2",
        owner = "blue",
        position = 71,
        infantry = 7,
        arty = 2,
    },
	{
        id = "B2",
        owner = "blue",
        position = 91,
        infantry = 7,
        arty = 2,
    },
	{
        id = "B2",
        owner = "blue",
        position = 111,
        infantry = 7,
        arty = 2,
    },
	{
        id = "B2",
        owner = "blue",
        position = 131,
        infantry = 7,
        arty = 2,
    },
	{
        id = "B2",
        owner = "blue",
        position = 151,
        infantry = 7,
        arty = 2,
    },
	{
        id = "B2",
        owner = "blue",
        position = 171,
        infantry = 7,
        arty = 2,
    },
	{
        id = "B2",
        owner = "blue",
        position = 191,
        infantry = 7,
        arty = 2,
    }
	
}
